package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/Nurs005/gql-yt/graph/model"
	thegraph "github.com/Nurs005/gql-yt/theGraph"
)

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context, where *model.AccountFilter) (*model.Account, error) {
	val, err := thegraph.FetchFromTheGraph(where)
	if err != nil {
		return nil, err
	}
	return val, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
